// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Playlist struct {
	ID            string
	Title         string
	Thumbnail     string
	Tracks        []string
	AllowedTracks []string
	Length        pgtype.Int4
	AllowedLength pgtype.Int4
}

type PlaylistPermission struct {
	PlaylistID string
	UserID     int64
	Role       interface{}
}

type Track struct {
	ID        string
	Title     string
	Authors   string
	Thumbnail string
	Length    int32
	Explicit  bool
}

type User struct {
	ID   int64
	Name string
}
