service: # изменять в случае изменений в .env
  database:
    host: "localhost"
    user: "user"
    password: "average_password"
    port: 5432
    name: "db"
    ssl-mode: "disable"

  #  redis:
  #    host: "app-redis"
  #    password: "WTkL5guyDOAd9me_DmCd"
  #    port: 6380

  backend:
    telegram-bot-token: "7536040116:AAHT7U-cl0q_YPbnoT8Ew1GWwdczwSTFhS8"

    certificate:
      cert-file: "/etc/letsencrypt/live/npm-1/fullchain.pem"
      key-file: "/etc/letsencrypt/live/npm-1/privkey.pem"

    port: 8080

    jwt:
      secret: "omMH41M5DKOmF8jhqIXUgY3doLU7C6PU++ynKOJqZwnPMDa2Uzu5eg1GGRfwXvLyWgmkBaIKqgM+YukO"
      access-token-expiration: "30" # в минутах
      refresh-token-expiration: "43200" #  30 дней в минутах

roles:
  user: [""]
  admin: [""]

settings:
  debug: true # включение / выключение дебага
  listen-tls: false # false - http, true - https (при первом старте до выпуска сертификатов - ставить false, после - true)
  timezone: "GMT+3" # часовой пояс в формате "GMT+3"