name: frontend-search
on:
  push:
    paths-ignore:
      - compose.yml
      - .gitignore
      - README.md
      - .github/workflows/backend.yml

jobs:
  build:
    defaults:
      run:
        working-directory: 'frontend/search'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    concurrency:
      group: 'pages'
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Shorten Commit Hash
        id: short_hash
        run: echo "HASH=${GITHUB_SHA:0:7}" >> "$GITHUB_OUTPUT"

      - name: Restore cached packages
        id: restore
        uses: actions/cache/restore@v4
        with:
          path: |
            frontend/search/node_modules
          key: packages

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.8.0'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'pnpm'
          cache-dependency-path: 'frontend/search/pnpm-lock.yaml'

      - name: Build and install deps
        run: pnpm install && pnpm run build

      - name: Save packages to cache
        uses: actions/cache/save@v4
        with:
          path: |
            frontend/search/node_modules
          key: ${{ steps.restore.outputs.cache-primary-key }}